import { mutation, query } from "./_generated/server";
import { v } from "convex/values";
import { requireBusinessAccess, requireUser } from "./helpers";

export const mine = query({ args:{}, handler:async ctx=>{ const user=await requireUser(ctx); if(user.isPlatformAdmin) return await ctx.db.query("businesses").collect(); const memberships=await ctx.db.query("memberships").withIndex("by_user",q=>q.eq("userId",user._id)).collect(); const rows=await Promise.all(memberships.map(async m=>await ctx.db.query("businesses").withIndex("by_organization",q=>q.eq("organizationId",m.organizationId)).collect())); return rows.flat(); }});
export const workspaceBySlug = query({ args:{slug:v.string()}, handler:async(ctx,{slug})=>{const business=await ctx.db.query("businesses").withIndex("by_slug",q=>q.eq("slug",slug)).unique();if(!business)return null;await requireBusinessAccess(ctx,business._id);const [logoUrl,iconUrl]=await Promise.all([business.logoStorageId?ctx.storage.getUrl(business.logoStorageId):null,business.iconStorageId?ctx.storage.getUrl(business.iconStorageId):null]);return{...business,logoUrl,iconUrl};}});
export const update = mutation({ args:{ businessId:v.id("businesses"),name:v.string(),websiteUrl:v.optional(v.string()),phone:v.optional(v.string()),address:v.optional(v.string()),primaryColor:v.string(),secondaryColor:v.optional(v.string()),isPublished:v.boolean() }, handler:async(ctx,args)=>{ await requireBusinessAccess(ctx,args.businessId); const {businessId,...values}=args; await ctx.db.patch(businessId,values); }});
export const generateUploadUrl=mutation({args:{businessId:v.id("businesses")},handler:async(ctx,{businessId})=>{await requireBusinessAccess(ctx,businessId);return await ctx.storage.generateUploadUrl();}});
export const saveBranding=mutation({args:{businessId:v.id("businesses"),logoStorageId:v.optional(v.id("_storage")),iconStorageId:v.optional(v.id("_storage")),primaryColor:v.string(),secondaryColor:v.optional(v.string())},handler:async(ctx,args)=>{await requireBusinessAccess(ctx,args.businessId);const{businessId,...values}=args;await ctx.db.patch(businessId,values);}});
