import { mutation, query } from "./_generated/server";
import { v } from "convex/values";
import { requireUser } from "./helpers";

async function secretsMatch(provided:string,expected:string){const encoder=new TextEncoder();const[left,right]=await Promise.all([crypto.subtle.digest("SHA-256",encoder.encode(provided)),crypto.subtle.digest("SHA-256",encoder.encode(expected))]);const a=new Uint8Array(left);const b=new Uint8Array(right);let difference=0;for(let index=0;index<a.length;index++)difference|=a[index]^b[index];return difference===0}

export const mine=query({args:{},handler:async ctx=>{const user=await requireUser(ctx);if(!user.isPlatformAdmin)throw new Error("Administrator access required");const settings=await ctx.db.query("resellerEmailSettings").withIndex("by_owner",q=>q.eq("ownerUserId",user._id)).unique();if(!settings)return null;const{smtpPasswordCiphertext,alertSmtpPasswordCiphertext,...safe}=settings;return{...safe,smtpPasswordConfigured:Boolean(smtpPasswordCiphertext),alertSmtpPasswordConfigured:Boolean(alertSmtpPasswordCiphertext)}}});

const settingsArgs={smtpHost:v.string(),smtpPort:v.number(),smtpUser:v.string(),smtpPasswordCiphertext:v.optional(v.string()),fromName:v.string(),fromEmail:v.string(),smtpTestRecipient:v.optional(v.string()),notifyEmailFailures:v.optional(v.boolean()),failureAlertEmail:v.optional(v.string()),alertSmtpHost:v.optional(v.string()),alertSmtpPort:v.optional(v.number()),alertSmtpUser:v.optional(v.string()),alertSmtpPasswordCiphertext:v.optional(v.string()),alertFromEmail:v.optional(v.string())};

export const saveSecure=mutation({args:settingsArgs,handler:async(ctx,args)=>{const user=await requireUser(ctx);if(!user.isPlatformAdmin)throw new Error("Administrator access required");const current=await ctx.db.query("resellerEmailSettings").withIndex("by_owner",q=>q.eq("ownerUserId",user._id)).unique();const values={...args,smtpHost:args.smtpHost.trim(),smtpUser:args.smtpUser.trim(),fromName:args.fromName.trim(),fromEmail:args.fromEmail.trim().toLowerCase(),smtpTestRecipient:args.smtpTestRecipient?.trim().toLowerCase(),failureAlertEmail:args.failureAlertEmail?.trim().toLowerCase(),alertSmtpHost:args.alertSmtpHost?.trim(),alertSmtpUser:args.alertSmtpUser?.trim(),alertFromEmail:args.alertFromEmail?.trim().toLowerCase()};if(current){await ctx.db.patch(current._id,values);return current._id}return await ctx.db.insert("resellerEmailSettings",{ownerUserId:user._id,...values})}});

export const acknowledgeAlerts=mutation({args:{},handler:async ctx=>{const user=await requireUser(ctx);if(!user.isPlatformAdmin)throw new Error("Administrator access required");const current=await ctx.db.query("resellerEmailSettings").withIndex("by_owner",q=>q.eq("ownerUserId",user._id)).unique();if(!current)throw new Error("Email settings are not configured");const alertsAcknowledgedAt=Date.now();await ctx.db.patch(current._id,{alertsAcknowledgedAt});return alertsAcknowledgedAt;}});

export const forDelivery=query({args:{secret:v.string()},handler:async(ctx,args)=>{const expected=process.env.ANALYTICS_INGEST_SECRET;if(!expected||!(await secretsMatch(args.secret,expected)))throw new Error("Invalid delivery credential");return await ctx.db.query("resellerEmailSettings").first()}});
