"use client";

import { FormEvent, useState } from "react";
import { useMutation, useQuery } from "convex/react";
import { api } from "../../convex/_generated/api";
import type { Id } from "../../convex/_generated/dataModel";
import { ReviewProvider, reviewPlatformCatalog } from "@/lib/demo-data";

type Draft={id?:Id<"reviewDestinations">;provider:ReviewProvider;name:string;reviewUrl:string;profileUrl:string};
const emptyDraft:Draft={provider:"google",name:"Google",reviewUrl:"",profileUrl:""};
function isHttpsUrl(value:string){try{return new URL(value).protocol==="https:"}catch{return false}}

export function DestinationManager({businessId}:{businessId:Id<"businesses">}){
  const rows=useQuery(api.destinations.listForBusiness,{businessId}); const upsert=useMutation(api.destinations.upsert); const remove=useMutation(api.destinations.remove);
  const [draft,setDraft]=useState<Draft>(emptyDraft);const[modalOpen,setModalOpen]=useState(false);const[error,setError]=useState("");const[busy,setBusy]=useState(false);
  const destinations=(rows??[]).sort((a,b)=>a.displayOrder-b.displayOrder);
  function openNew(){setDraft(emptyDraft);setError("");setModalOpen(true)}
  function changeProvider(provider:ReviewProvider){const platform=reviewPlatformCatalog.find(item=>item.provider===provider)!;setDraft(current=>({...current,provider,name:platform.name}))}
  async function saveRow(row:{_id:Id<"reviewDestinations">;provider:ReviewProvider;label:string;reviewUrl:string;profileUrl?:string;displayOrder:number;isEnabled:boolean},changes={}){await upsert({id:row._id,businessId,provider:row.provider,label:row.label,reviewUrl:row.reviewUrl,profileUrl:row.profileUrl,displayOrder:row.displayOrder,isEnabled:row.isEnabled,...changes})}
  async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!isHttpsUrl(draft.reviewUrl)||(draft.profileUrl&&!isHttpsUrl(draft.profileUrl))){setError("Please enter complete https:// links.");return}setBusy(true);try{const current=draft.id?destinations.find(row=>row._id===draft.id):undefined;await upsert({id:draft.id,businessId,provider:draft.provider,label:draft.name.trim(),reviewUrl:draft.reviewUrl.trim(),profileUrl:draft.profileUrl.trim()||undefined,displayOrder:current?.displayOrder??destinations.length,isEnabled:current?.isEnabled??true});setModalOpen(false)}catch(error){setError(error instanceof Error?error.message:"Review site could not be saved.")}finally{setBusy(false)}}
  async function move(index:number,direction:-1|1){const target=index+direction;if(target<0||target>=destinations.length)return;await Promise.all([saveRow(destinations[index] as any,{displayOrder:target}),saveRow(destinations[target] as any,{displayOrder:index})])}
  return <><div className="section-heading"><div><span className="eyebrow">Where reviews happen</span><h2>Review sites</h2></div><button className="button primary" onClick={openNew}>+ Add platform</button></div><p className="panel-intro">Changes are saved to this client account and immediately become available to the published funnel.</p><div className="destination-list">{destinations.map((destination,index)=><div className="destination" key={destination._id}><span className="source-icon" style={{background:reviewPlatformCatalog.find(p=>p.provider===destination.provider)?.color}}>{destination.label[0]}</span><div><strong>{destination.label}</strong><small>{destination.reviewUrl}</small></div><div className="destination-actions"><button className={`toggle ${destination.isEnabled?"on":""}`} aria-label={`${destination.isEnabled?"Disable":"Enable"} ${destination.label}`} onClick={()=>saveRow(destination as any,{isEnabled:!destination.isEnabled})}><span/></button><button className="small-action" onClick={()=>move(index,-1)} disabled={index===0}>↑</button><button className="small-action" onClick={()=>move(index,1)} disabled={index===destinations.length-1}>↓</button><button className="small-action text-action" onClick={()=>{setDraft({id:destination._id,provider:destination.provider,name:destination.label,reviewUrl:destination.reviewUrl,profileUrl:destination.profileUrl??""});setModalOpen(true)}}>Edit</button><button className="small-action danger" onClick={()=>remove({id:destination._id})}>Delete</button></div></div>)}{rows===undefined&&<div className="empty-state">Loading review sites…</div>}{rows&&rows.length===0&&<div className="empty-state">No review sites yet.</div>}</div>{modalOpen&&<div className="modal-backdrop"><section className="modal-card"><button className="modal-close" onClick={()=>setModalOpen(false)}>×</button><h2>{draft.id?"Edit review platform":"Add a review platform"}</h2><form onSubmit={submit}><label>Platform<select value={draft.provider} onChange={event=>changeProvider(event.target.value as ReviewProvider)}>{reviewPlatformCatalog.map(platform=><option key={platform.provider} value={platform.provider}>{platform.name}</option>)}</select></label>{draft.provider==="custom"&&<label>Platform name<input value={draft.name} onChange={event=>setDraft({...draft,name:event.target.value})}/></label>}<label>Direct write-review link<input value={draft.reviewUrl} onChange={event=>setDraft({...draft,reviewUrl:event.target.value})} placeholder="https://..."/></label><label>Review source/profile URL <span>(optional)</span><input value={draft.profileUrl} onChange={event=>setDraft({...draft,profileUrl:event.target.value})} placeholder="https://..."/></label>{error&&<div className="form-error">{error}</div>}<div className="modal-actions"><button type="button" className="button" onClick={()=>setModalOpen(false)}>Cancel</button><button className="button primary" disabled={busy}>{busy?"Saving…":"Save platform"}</button></div></form></section></div>}</>;
}
