"use client";

import { CSSProperties, useEffect, useState } from "react";
import { businessBrandingStorageKey, defaultBusinessBranding, defaultPrintSettings, demoBusiness, PrintSettings, printSettingsStorageKey } from "@/lib/demo-data";

export function PrintCardPreview({ slug, qrSuffix }: { slug: string; qrSuffix: string }) {
  const [settings, setSettings] = useState(defaultPrintSettings);
  useEffect(() => { const value = localStorage.getItem(printSettingsStorageKey); if (value) try { const stored = JSON.parse(value) as PrintSettings; const badges = stored.platformBadges?.includes("google-yelp") ? [...stored.platformBadges.filter(id => id !== "google-yelp"), "google", "yelp"] : stored.platformBadges; const migrated = { ...stored, ...(stored.title === "How was your experience?" ? { title:defaultPrintSettings.title } : {}), ...(stored.subtitle === "Scan to share your feedback. It only takes a minute." ? { subtitle:defaultPrintSettings.subtitle } : {}) }; setSettings({ ...defaultPrintSettings, ...migrated, ...(badges ? { platformBadges: [...new Set(badges)] } : {}) }); } catch {} }, []);
  return <div className="print-sheet"><div><span>Front</span><CardArtwork face="front" settings={settings} slug={slug} qrSuffix={qrSuffix} /></div><div className="print-break"><span>Back</span><CardArtwork face="back" settings={settings} slug={slug} qrSuffix={qrSuffix} /></div></div>;
}

export function CardArtwork({ face, settings, slug = demoBusiness.slug, qrSuffix = ".svg", compact = false }: { face:"front"|"back"; settings:PrintSettings; slug?:string; qrSuffix?:string; compact?:boolean }) {
  const [branding,setBranding]=useState(defaultBusinessBranding); useEffect(()=>{const load=()=>{const value=localStorage.getItem(businessBrandingStorageKey);if(value)try{setBranding({...defaultBusinessBranding,...JSON.parse(value)})}catch{}};load();window.addEventListener("myroi-branding-updated",load);return()=>window.removeEventListener("myroi-branding-updated",load)},[]);
  const style = { "--card-title-scale": settings.titleSize / 37, "--card-subtitle-scale": settings.subtitleSize / 17, "--card-title-color": settings.titleColor, "--card-back-title-scale": settings.backTitleSize / 44, "--card-back-subtitle-scale": settings.backSubtitleSize / 18, "--card-back-title-color": settings.backTitleColor, "--client-primary": branding.primaryColor, "--client-secondary": branding.secondaryColor } as CSSProperties;
  if (face === "back") return <section className={`review-card card-back ${compact ? "compact-card" : ""}`} style={style}><div className="back-brand"><img src={branding.logoUrl} alt={`${demoBusiness.name} logo`} /></div><div className="back-message"><h1>{settings.backTitle}</h1><p>{settings.backSubtitle}</p><small>{settings.backFooter}</small></div></section>;
  return <section className={`review-card ${compact ? "compact-card" : ""}`} style={style} aria-label={`${demoBusiness.name} review request card`}><div className="review-card-grid"><div className="review-card-copy"><img src={branding.logoUrl} alt={`${demoBusiness.name} logo`} /><h1>{settings.title}</h1><p>{settings.subtitle}</p><div className="contact-lines"><span>{settings.phone}</span><span>{settings.website}</span></div></div><div className="card-qr"><div className="qr-art"><img src={`/api/qr/${slug}${qrSuffix}`} alt="QR code with business icon to leave a review" /><span><img src={branding.iconUrl} alt="" /></span></div><strong>{settings.scanLabel}</strong><div className="platform-logo-stack">{settings.platformBadges.includes("google") && <img src="/brands/review-us-google.svg" alt="Review us on Google" />}{settings.platformBadges.includes("yelp") && <img src="/brands/review-us-yelp.svg" alt="Review us on Yelp" />}</div></div></div></section>;
}
