"use client";

import { ChangeEvent, useEffect, useState } from "react";
import { AdminClients } from "@/components/admin-clients";
import { pilotClientsStorageKey, resellerSettingsStorageKey } from "@/lib/demo-data";
import { ResellerAnalytics, ResellerEmailHealth } from "@/components/analytics-dashboard";
import { readPilotEmailLog, recordPilotEmail } from "@/lib/pilot-tracking";

type Tab = "overview" | "clients" | "analytics" | "branding" | "email";
type ResellerSettings = { businessName:string; logoUrl:string; iconUrl:string; supportEmail:string; website:string; smtpHost:string; smtpPort:string; smtpUser:string; fromName:string; fromEmail:string; notifyEmailFailures:boolean; failureAlertEmail:string; alertSmtpHost:string; alertSmtpUser:string; alertFromEmail:string };
type EmailStatus = { configured:boolean; missing:string[]; smtpHostConfigured:boolean; smtpUserConfigured:boolean; smtpPasswordConfigured:boolean; smtpFromEmailConfigured:boolean; smtpTestRecipientConfigured:boolean; alertSmtpPasswordConfigured:boolean };
const defaults:ResellerSettings = { businessName:"myROIagency", logoUrl:"/brands/myroiagency-logo.png", iconUrl:"/brands/myroiagency-mark.png", supportEmail:"support-team@myroiagency.com", website:"https://www.myroiagency.com", smtpHost:"", smtpPort:"587", smtpUser:"", fromName:"myROIagency Reviews", fromEmail:"", notifyEmailFailures:true, failureAlertEmail:"support-team@myroiagency.com", alertSmtpHost:"", alertSmtpUser:"", alertFromEmail:"" };

export function ResellerAdmin() {
  const [tab,setTab] = useState<Tab>("overview"); const [settings,setSettings] = useState(defaults); const [saved,setSaved] = useState(false); const [clientCount,setClientCount] = useState(1); const [alertCount,setAlertCount] = useState(0); const [emailStatus,setEmailStatus] = useState<EmailStatus|null>(null); const [testingEmail,setTestingEmail] = useState(false); const [testResult,setTestResult] = useState("");
  useEffect(()=>{ const value=localStorage.getItem(resellerSettingsStorageKey); if(value) try{setSettings({...defaults,...JSON.parse(value)})}catch{} },[]);
  useEffect(()=>{const load=()=>{const value=localStorage.getItem(pilotClientsStorageKey);if(!value){setClientCount(1);return}try{const clients=JSON.parse(value) as unknown[];setClientCount(Math.max(1,clients.length))}catch{setClientCount(1)}};load();window.addEventListener("myroi-clients-updated",load);window.addEventListener("storage",load);return()=>{window.removeEventListener("myroi-clients-updated",load);window.removeEventListener("storage",load)}},[]);
  useEffect(()=>{const load=()=>setAlertCount(readPilotEmailLog().filter(row=>row.status!=="sent").length);load();window.addEventListener("myroi-email-log-updated",load);return()=>window.removeEventListener("myroi-email-log-updated",load)},[]);
  useEffect(()=>{void refreshEmailStatus()},[]);
  function change(event:ChangeEvent<HTMLInputElement>){ const key=event.target.name as keyof ResellerSettings; setSettings(current=>({...current,[key]:event.target.type==="checkbox"?event.target.checked:event.target.value})); setSaved(false); }
  function upload(event:ChangeEvent<HTMLInputElement>, key:"logoUrl"|"iconUrl") { const file=event.target.files?.[0]; if(!file)return; const reader=new FileReader(); reader.onload=()=>{setSettings(current=>({...current,[key]:String(reader.result)}));setSaved(false)}; reader.readAsDataURL(file); }
  function save(){localStorage.setItem(resellerSettingsStorageKey,JSON.stringify(settings));setSaved(true)}
  async function refreshEmailStatus(){try{const response=await fetch("/api/email-status",{cache:"no-store"});if(response.ok)setEmailStatus(await response.json() as EmailStatus)}catch{setEmailStatus(null)}}
  async function testEmail(){setTestingEmail(true);setTestResult("");try{const response=await fetch("/api/admin/smtp-test",{method:"POST",headers:{"content-type":"application/json"},body:"{}"});const result=await response.json().catch(()=>({})) as {sent?:boolean;recipient?:string;error?:string;missing?:string[]};const error=result.missing?.length?`Missing Worker variables: ${result.missing.join(", ")}`:result.error;if(!response.ok||!result.sent)throw new Error(error??"SMTP test failed.");setTestResult(`Test email sent to ${result.recipient}.`);recordPilotEmail({kind:"smtp_test",status:"sent",recipient:result.recipient??"configured test recipient",subject:"myROI Reviews SMTP test"})}catch(error){const problem=error instanceof Error?error.message:"SMTP test failed.";setTestResult(problem);recordPilotEmail({kind:"smtp_test",status:"failed",recipient:"configured test recipient",subject:"myROI Reviews SMTP test",error:problem})}finally{setTestingEmail(false);await refreshEmailStatus()}}
  return <main className="reseller-shell"><aside className="reseller-sidebar"><a className="platform-brand" href="/"><img src={settings.logoUrl} alt={`${settings.businessName} logo`}/><span>Reviews</span></a><small>Main reseller login</small><nav><button className={tab==="overview"?"active":""} onClick={()=>setTab("overview")}>Overview</button><button className={tab==="clients"?"active":""} onClick={()=>setTab("clients")}>Client accounts & users</button><button className={tab==="analytics"?"active":""} onClick={()=>setTab("analytics")}>System alerts & email log{alertCount>0&&<span className="alert-menu-badge">{alertCount}</span>}</button><button className={tab==="branding"?"active":""} onClick={()=>setTab("branding")}>Reseller business setup</button><button className={tab==="email"?"active":""} onClick={()=>setTab("email")}>Master email service</button></nav></aside><section className="reseller-workspace"><header className="topbar"><div className="business-avatar myroi-avatar"><img src={settings.iconUrl} alt=""/></div><div><strong>{settings.businessName}</strong><small>Platform administrator · {settings.supportEmail}</small></div></header><div className="admin-content">
    {tab==="overview"&&<><span className="eyebrow">Main reseller dashboard</span><h1>Platform health at a glance</h1><p className="lede">Manage client accounts, reseller branding, and the shared email-delivery service. Client funnel performance stays inside each client workspace.</p><ResellerEmailHealth openLog={()=>setTab("analytics")}/><div className="metric-grid"><article><span>Client accounts</span><strong>{clientCount}</strong><small>{clientCount === 1 ? "Yorkshire Roofing active" : `${clientCount} accounts saved in this pilot`}</small></article><article><span>Master email service</span><strong>{emailStatus?.configured?"Ready":"Setup"}</strong><small>{emailStatus?.configured?"Worker runtime is fully configured":emailStatus?.missing?.length?`Missing: ${emailStatus.missing.join(", ")}`:"Checking Worker configuration…"}</small></article><article><span>System alerts</span><strong>{alertCount}</strong><small>{alertCount?"Delivery attempts need attention":"No active delivery warnings"}</small></article></div><section className="panel"><div className="section-heading"><div><span className="eyebrow">Quick start</span><h2>Reseller setup</h2></div></div><div className="setup-checklist"><button onClick={()=>setTab("branding")}><b>1</b><span><strong>Add your business identity</strong><small>Logo, name, support address, and website</small></span></button><button onClick={()=>setTab("email")}><b>2</b><span><strong>Connect the master email service</strong><small>Every client notification is sent from this account</small></span></button><button onClick={()=>setTab("clients")}><b>3</b><span><strong>Add clients and users</strong><small>Email invitations are optional during setup</small></span></button></div></section></>}
    {tab==="clients"&&<><span className="eyebrow">Accounts</span><h1>Clients & users</h1><p className="lede">Create the account yourself or send an invitation when you want the customer to finish setup.</p><section className="panel"><AdminClients/></section></>}
    {tab==="analytics"&&<><span className="eyebrow">Platform monitoring</span><h1>System alerts & email health</h1><p className="lede">Investigate unsuccessful deliveries from the shared email service. Funnel visits, QR scans, forms, and review clicks remain in the appropriate client dashboard.</p><section className="panel"><ResellerAnalytics/></section></>}
    {tab==="branding"&&<><span className="eyebrow">Reseller identity</span><h1>Business setup</h1><p className="lede">These details identify your reseller portal and system email.</p><section className="panel"><div className="branding-upload-row"><div className="brand-upload"><img src={settings.logoUrl} alt="myROIagency logo"/><label className="button file-button">Replace main logo<input type="file" accept="image/*" onChange={event=>upload(event,"logoUrl")}/></label><small>Full horizontal or wordmark logo.</small></div><div className="brand-upload square"><img src={settings.iconUrl} alt="myROIagency icon"/><label className="button file-button">Replace square icon<input type="file" accept="image/*" onChange={event=>upload(event,"iconUrl")}/></label><small>Separate asset for compact spaces and QR codes.</small></div></div><div className="settings-grid"><label>Business name<input name="businessName" value={settings.businessName} onChange={change}/></label><label>Support email<input name="supportEmail" type="email" value={settings.supportEmail} onChange={change}/></label><label>Website<input name="website" value={settings.website} onChange={change}/></label></div><SaveRow saved={saved} save={save}/></section></>}
    {tab==="email"&&<><span className="eyebrow">Shared delivery service</span><h1>Master email service</h1><p className="lede">All client notifications use this sender. Each client selects its own recipient and notification types inside its client dashboard.</p><section className="panel">
      <div className="smtp-note"><strong>Production values live in the Worker runtime</strong><span>Add the exact variable names below under the deployed Worker’s <b>Settings → Variables and Secrets</b>. Store <code>SMTP_PASSWORD</code> as an encrypted secret; the other values can be ordinary variables.</span><a className="button secret-link" href="https://dash.cloudflare.com/f53f7bb64c38f8d9100945b4de2d1d85/workers/services/view/myroi-reviews/production/settings" target="_blank" rel="noreferrer">Open Worker settings</a></div>
      <div className="runtime-status"><strong>{emailStatus?.configured?"Master SMTP is fully configured":"Master SMTP needs attention"}</strong><span>{!emailStatus?"Checking the deployed Worker…":emailStatus.missing.length?`Missing in the deployed Worker: ${emailStatus.missing.join(", ")}`:"All four required delivery values are visible to the Worker."}</span></div>
      <div className="secret-checklist">
        <StatusItem label="SMTP server" code="SMTP_HOST" ready={emailStatus?.smtpHostConfigured}/><StatusItem label="SMTP username" code="SMTP_USER" ready={emailStatus?.smtpUserConfigured}/><StatusItem label="SMTP password" code="SMTP_PASSWORD" ready={emailStatus?.smtpPasswordConfigured}/><StatusItem label="Sender address" code="SMTP_FROM_EMAIL" ready={emailStatus?.smtpFromEmailConfigured}/><StatusItem label="Test recipient" code="SMTP_TEST_TO" ready={emailStatus?.smtpTestRecipientConfigured}/><StatusItem label="Backup-alert password" code="ALERT_SMTP_PASSWORD" ready={emailStatus?.alertSmtpPasswordConfigured} optional/>
      </div>
      <p className="secret-path"><strong>Important:</strong> values typed into the form below are saved as reseller preferences in this pilot browser. They do not replace the Worker runtime variables used to send mail.</p>
      <div className="smtp-test-card"><div><h3>Test the production connection</h3><p>This verifies the SMTP login and sends one message to <code>SMTP_TEST_TO</code> (or <code>SMTP_FAILURE_ALERT_TO</code> as a fallback).</p>{testResult&&<strong className="test-result">{testResult}</strong>}</div><button className="button primary" disabled={testingEmail} onClick={testEmail}>{testingEmail?"Testing…":"Send test email"}</button></div>
      <h3>Master sender preferences</h3><div className="settings-grid compact-settings"><label>SMTP host<input name="smtpHost" placeholder="smtp.office365.com" value={settings.smtpHost} onChange={change}/></label><label>Port<input name="smtpPort" value={settings.smtpPort} onChange={change}/></label><label>Username<input name="smtpUser" value={settings.smtpUser} onChange={change}/></label><label>From name<input name="fromName" value={settings.fromName} onChange={change}/></label><label>From email<input name="fromEmail" type="email" value={settings.fromEmail} onChange={change}/></label></div>
      <div className="alert-smtp-section"><h3>Independent delivery-failure alerts</h3><p>A separate provider is recommended so an outage in the master service cannot suppress its own warning.</p><div className="settings-grid compact-settings"><label>Reseller alert recipient<input name="failureAlertEmail" type="email" value={settings.failureAlertEmail} onChange={change}/></label><label>Backup SMTP host<input name="alertSmtpHost" value={settings.alertSmtpHost} onChange={change}/></label><label>Backup SMTP user<input name="alertSmtpUser" value={settings.alertSmtpUser} onChange={change}/></label><label>Backup from email<input name="alertFromEmail" type="email" value={settings.alertFromEmail} onChange={change}/></label></div><label className="check-row"><input type="checkbox" name="notifyEmailFailures" checked={settings.notifyEmailFailures} onChange={change}/> Alert the reseller administrator when the master delivery service fails</label></div><SaveRow saved={saved} save={save}/>
    </section></>}
  </div></section></main>;
}

function SaveRow({saved,save}:{saved:boolean;save:()=>void}){return <div className="settings-save"><small>{saved?"Saved in this pilot browser.":"Production saves this for the reseller account."}</small><button className="button primary" onClick={save}>Save settings</button></div>}
function StatusItem({label,code,ready,optional=false}:{label:string;code:string;ready?:boolean;optional?:boolean}){return <div><span>{label}</span><strong className={ready?"secret-ready":"secret-missing"}>{ready?"Configured":optional?"Optional":"Missing"}</strong><code>{code}</code></div>}
