"use client";

import { ChangeEvent, useEffect, useRef, useState } from "react";
import { useMutation, useQuery } from "convex/react";
import { api } from "../../convex/_generated/api";
import { AdminClients } from "@/components/admin-clients";
import { ResellerAnalytics, ResellerEmailHealth } from "@/components/analytics-dashboard";
import type { Id } from "../../convex/_generated/dataModel";

type Tab = "overview" | "clients" | "analytics" | "branding" | "email";
type ResellerSettings = { businessName:string; logoUrl:string; iconUrl:string; supportEmail:string; website:string; smtpHost:string; smtpPort:string; smtpUser:string; smtpPassword:string; smtpPasswordConfigured:boolean; smtpTestRecipient:string; fromName:string; fromEmail:string; notifyEmailFailures:boolean; failureAlertEmail:string; alertSmtpHost:string; alertSmtpPort:string; alertSmtpUser:string; alertSmtpPassword:string; alertSmtpPasswordConfigured:boolean; alertFromEmail:string };
type EmailStatus = { configured:boolean; missing:string[]; smtpHostConfigured:boolean; smtpUserConfigured:boolean; smtpPasswordConfigured:boolean; smtpFromEmailConfigured:boolean; smtpTestRecipientConfigured:boolean; alertSmtpPasswordConfigured:boolean };
const defaults:ResellerSettings = { businessName:"myROIagency", logoUrl:"/brands/myroiagency-logo.png", iconUrl:"/brands/myroiagency-mark.png", supportEmail:"support-team@myroiagency.com", website:"https://www.myroiagency.com", smtpHost:"", smtpPort:"587", smtpUser:"", smtpPassword:"", smtpPasswordConfigured:false, smtpTestRecipient:"", fromName:"myROIagency Reviews", fromEmail:"", notifyEmailFailures:true, failureAlertEmail:"support-team@myroiagency.com", alertSmtpHost:"", alertSmtpPort:"587", alertSmtpUser:"", alertSmtpPassword:"", alertSmtpPasswordConfigured:false, alertFromEmail:"" };

export function ResellerAdmin() {
  const currentUser=useQuery(api.accounts.current,{});const businesses=useQuery(api.businesses.mine,currentUser?{}:"skip");const bootstrapYorkshire=useMutation(api.accounts.bootstrapYorkshire);const bootstrapped=useRef(false);
  const reseller=useQuery(api.reseller.mine,currentUser?.isPlatformAdmin?{}:"skip");const emailPreferences=useQuery(api.emailSettings.mine,currentUser?.isPlatformAdmin?{}:"skip");const systemLog=useQuery(api.analytics.resellerOverview,currentUser?.isPlatformAdmin?{}:"skip");
  const saveReseller=useMutation(api.reseller.save);const generateUploadUrl=useMutation(api.reseller.generateUploadUrl);
  const [tab,setTab] = useState<Tab>("overview"); const [settings,setSettings] = useState(defaults); const [files,setFiles]=useState<{logo?:File;icon?:File}>({}); const [saved,setSaved] = useState(false); const [clientCount,setClientCount] = useState(1); const [emailStatus,setEmailStatus] = useState<EmailStatus|null>(null); const [testingEmail,setTestingEmail] = useState(false); const [testResult,setTestResult] = useState("");
  useEffect(()=>{if(reseller)setSettings(current=>({...current,businessName:reseller.businessName,supportEmail:reseller.supportEmail,website:reseller.website,logoUrl:reseller.logoUrl??current.logoUrl,iconUrl:reseller.iconUrl??current.iconUrl}))},[reseller]);
  useEffect(()=>{if(emailPreferences)setSettings(current=>({...current,smtpHost:emailPreferences.smtpHost,smtpPort:String(emailPreferences.smtpPort),smtpUser:emailPreferences.smtpUser,smtpPasswordConfigured:emailPreferences.smtpPasswordConfigured,smtpTestRecipient:emailPreferences.smtpTestRecipient??"",fromName:emailPreferences.fromName,fromEmail:emailPreferences.fromEmail,notifyEmailFailures:emailPreferences.notifyEmailFailures??true,failureAlertEmail:emailPreferences.failureAlertEmail??"",alertSmtpHost:emailPreferences.alertSmtpHost??"",alertSmtpPort:String(emailPreferences.alertSmtpPort??587),alertSmtpUser:emailPreferences.alertSmtpUser??"",alertSmtpPasswordConfigured:emailPreferences.alertSmtpPasswordConfigured,alertFromEmail:emailPreferences.alertFromEmail??""}))},[emailPreferences]);
  useEffect(()=>{if(businesses)setClientCount(businesses.length)},[businesses]);
  useEffect(()=>{if(!currentUser?.isPlatformAdmin||businesses===undefined||businesses.length||bootstrapped.current)return;bootstrapped.current=true;void bootstrapYorkshire().catch(()=>{bootstrapped.current=false})},[currentUser,businesses,bootstrapYorkshire]);
  const alertCount=systemLog?.emails.filter(row=>row.status!=="sent").length??0;
  useEffect(()=>{if(currentUser?.isPlatformAdmin)void refreshEmailStatus()},[currentUser?.isPlatformAdmin]);
  if(currentUser===undefined)return <main className="login-page"><section className="login-card"><h1>Loading secure dashboard…</h1></section></main>;
  if(!currentUser?.isPlatformAdmin)return <main className="login-page"><section className="login-card"><h1>Administrator access required</h1><p>This signed-in account is not listed as a myROIagency platform administrator.</p><a className="button" href="/sign-out">Sign out</a></section></main>;
  function change(event:ChangeEvent<HTMLInputElement>){ const key=event.target.name as keyof ResellerSettings; setSettings(current=>({...current,[key]:event.target.type==="checkbox"?event.target.checked:event.target.value})); setSaved(false); }
  function upload(event:ChangeEvent<HTMLInputElement>, key:"logoUrl"|"iconUrl") { const file=event.target.files?.[0]; if(!file)return;setFiles(current=>({...current,[key==="logoUrl"?"logo":"icon"]:file})); const reader=new FileReader(); reader.onload=()=>{setSettings(current=>({...current,[key]:String(reader.result)}));setSaved(false)}; reader.readAsDataURL(file); }
  async function store(file?:File){if(!file)return undefined;const url=await generateUploadUrl({});const response=await fetch(url,{method:"POST",headers:{"Content-Type":file.type},body:file});if(!response.ok)throw new Error("The image upload failed.");return (await response.json() as {storageId:Id<"_storage">}).storageId}
  async function save(){setSaved(false);setTestResult("");try{if(tab==="email"){await persistEmailSettings()}else{const[logoStorageId,iconStorageId]=await Promise.all([store(files.logo),store(files.icon)]);await saveReseller({businessName:settings.businessName,supportEmail:settings.supportEmail,website:settings.website,...(logoStorageId?{logoStorageId}:{}),...(iconStorageId?{iconStorageId}:{})});setFiles({})}setSaved(true)}catch(error){setTestResult(error instanceof Error?error.message:"Settings could not be saved.")}}
  async function persistEmailSettings(){
    const response=await fetch("/api/admin/smtp-settings",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({smtpHost:settings.smtpHost,smtpPort:Number(settings.smtpPort)||587,smtpUser:settings.smtpUser,...(settings.smtpPassword?{smtpPassword:settings.smtpPassword}:{}),fromName:settings.fromName,fromEmail:settings.fromEmail,smtpTestRecipient:settings.smtpTestRecipient,notifyEmailFailures:settings.notifyEmailFailures,failureAlertEmail:settings.failureAlertEmail,alertSmtpHost:settings.alertSmtpHost,alertSmtpPort:Number(settings.alertSmtpPort)||587,alertSmtpUser:settings.alertSmtpUser,...(settings.alertSmtpPassword?{alertSmtpPassword:settings.alertSmtpPassword}:{}),alertFromEmail:settings.alertFromEmail})});
    const result=await response.json().catch(()=>({})) as {error?:string;passwordConfigured?:boolean;alertPasswordConfigured?:boolean};if(!response.ok)throw new Error(result.error??"SMTP settings could not be saved.");
    setSettings(current=>({...current,smtpPassword:"",smtpPasswordConfigured:result.passwordConfigured??current.smtpPasswordConfigured,alertSmtpPassword:"",alertSmtpPasswordConfigured:result.alertPasswordConfigured??current.alertSmtpPasswordConfigured}));await refreshEmailStatus();
  }
  async function refreshEmailStatus(){try{const response=await fetch("/api/email-status",{cache:"no-store"});if(response.ok)setEmailStatus(await response.json() as EmailStatus)}catch{setEmailStatus(null)}}
  async function testEmail(target:"primary"|"backup"="primary"){setTestingEmail(true);setTestResult("");try{await persistEmailSettings();const response=await fetch("/api/admin/smtp-test",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({target})});const result=await response.json().catch(()=>({})) as {sent?:boolean;recipient?:string;transport?:string;error?:string;missing?:string[]};const error=result.missing?.length?`Missing: ${result.missing.join(", ")}`:result.error;if(!response.ok||!result.sent)throw new Error(error??`${target} email test failed.`);setSaved(true);setTestResult(`${target==="backup"?"Backup":"Primary"} test sent to ${result.recipient} via ${result.transport==="mailjet_api"?"Mailjet API":"SMTP"}.`)}catch(error){setTestResult(error instanceof Error?error.message:`${target} email test failed.`)}finally{setTestingEmail(false);await refreshEmailStatus()}}
  return <main className="reseller-shell"><aside className="reseller-sidebar"><a className="platform-brand" href="/"><img src={settings.logoUrl} alt={`${settings.businessName} logo`}/><span>Reviews</span></a><small>Main reseller login</small><nav><button className={tab==="overview"?"active":""} onClick={()=>setTab("overview")}>Overview</button><button className={tab==="clients"?"active":""} onClick={()=>setTab("clients")}>Client accounts & users</button><button className={tab==="analytics"?"active":""} onClick={()=>setTab("analytics")}>System alerts & email log{alertCount>0&&<span className="alert-menu-badge">{alertCount}</span>}</button><button className={tab==="branding"?"active":""} onClick={()=>setTab("branding")}>Reseller business setup</button><button className={tab==="email"?"active":""} onClick={()=>setTab("email")}>Master email service</button></nav></aside><section className="reseller-workspace"><header className="topbar"><div className="business-avatar myroi-avatar"><img src={settings.iconUrl} alt=""/></div><div><strong>{settings.businessName}</strong><small>Platform administrator · {settings.supportEmail}</small></div></header><div className="admin-content">
    {tab==="overview"&&<><span className="eyebrow">Main reseller dashboard</span><h1>Platform health at a glance</h1><p className="lede">Manage client accounts, reseller branding, and the shared email-delivery service. Client funnel performance stays inside each client workspace.</p><ResellerEmailHealth openLog={()=>setTab("analytics")}/><div className="metric-grid"><article><span>Client accounts</span><strong>{clientCount}</strong><small>{clientCount === 1 ? "Yorkshire Roofing active" : `${clientCount} client accounts`}</small></article><article><span>Master email service</span><strong>{emailStatus?.configured?"Ready":"Setup"}</strong><small>{emailStatus?.configured?"Worker runtime is fully configured":emailStatus?.missing?.length?`Missing: ${emailStatus.missing.join(", ")}`:"Checking Worker configuration…"}</small></article><article><span>System alerts</span><strong>{alertCount}</strong><small>{alertCount?"Delivery attempts need attention":"No active delivery warnings"}</small></article></div><section className="panel"><div className="section-heading"><div><span className="eyebrow">Quick start</span><h2>Reseller setup</h2></div></div><div className="setup-checklist"><button onClick={()=>setTab("branding")}><b>1</b><span><strong>Add your business identity</strong><small>Logo, name, support address, and website</small></span></button><button onClick={()=>setTab("email")}><b>2</b><span><strong>Connect the master email service</strong><small>Every client notification is sent from this account</small></span></button><button onClick={()=>setTab("clients")}><b>3</b><span><strong>Add clients and users</strong><small>Email invitations are optional during setup</small></span></button></div></section></>}
    {tab==="clients"&&<><span className="eyebrow">Accounts</span><h1>Clients & users</h1><p className="lede">Create the account yourself or send an invitation when you want the customer to finish setup.</p><section className="panel"><AdminClients connected/></section></>}
    {tab==="analytics"&&<><span className="eyebrow">Platform monitoring</span><h1>System alerts & email health</h1><p className="lede">Investigate unsuccessful deliveries from the shared email service. Funnel visits, QR scans, forms, and review clicks remain in the appropriate client dashboard.</p><section className="panel"><ResellerAnalytics/></section></>}
    {tab==="branding"&&<><span className="eyebrow">Reseller identity</span><h1>Business setup</h1><p className="lede">These details identify your reseller portal and system email.</p><section className="panel"><div className="branding-upload-row"><div className="brand-upload"><img src={settings.logoUrl} alt="myROIagency logo"/><label className="button file-button">Replace main logo<input type="file" accept="image/*" onChange={event=>upload(event,"logoUrl")}/></label><small>Full horizontal or wordmark logo.</small></div><div className="brand-upload square"><img src={settings.iconUrl} alt="myROIagency icon"/><label className="button file-button">Replace square icon<input type="file" accept="image/*" onChange={event=>upload(event,"iconUrl")}/></label><small>Separate asset for compact spaces and QR codes.</small></div></div><div className="settings-grid"><label>Business name<input name="businessName" value={settings.businessName} onChange={change}/></label><label>Support email<input name="supportEmail" type="email" value={settings.supportEmail} onChange={change}/></label><label>Website<input name="website" value={settings.website} onChange={change}/></label></div><SaveRow saved={saved} save={save}/></section></>}
    {tab==="email"&&<><span className="eyebrow">Shared delivery service</span><h1>Master email service</h1><p className="lede">All client notifications use this sender. Each client selects its own recipient and notification types inside its client dashboard.</p><section className="panel">
      <div className="smtp-note"><strong>Enter the provider details once</strong><span>The complete master SMTP configuration is saved from this dashboard. Passwords are encrypted by the production Worker before storage and are never returned to the browser.</span></div>
      <div className="runtime-status"><strong>{emailStatus?.configured?"Master SMTP is fully configured":"Master SMTP needs attention"}</strong><span>{!emailStatus?"Checking the saved configuration…":emailStatus.missing.length?`Still needed: ${emailStatus.missing.join(", ")}`:"The saved connection is ready for a delivery test."}</span></div>
      <div className="secret-checklist">
        <StatusItem label="SMTP server" code="Dashboard setting" ready={emailStatus?.smtpHostConfigured}/><StatusItem label="SMTP username" code="Dashboard setting" ready={emailStatus?.smtpUserConfigured}/><StatusItem label="SMTP password" code="Encrypted credential" ready={emailStatus?.smtpPasswordConfigured}/><StatusItem label="Sender address" code="Dashboard setting" ready={emailStatus?.smtpFromEmailConfigured}/><StatusItem label="Test recipient" code="Dashboard setting" ready={emailStatus?.smtpTestRecipientConfigured}/><StatusItem label="Backup-alert password" code="Encrypted credential" ready={emailStatus?.alertSmtpPasswordConfigured} optional/>
      </div>
      <div className="smtp-test-card"><div><h3>Test production email delivery</h3><p>Saves the values below and sends one real message through the primary provider. Mailjet is sent through its HTTPS API for Cloudflare compatibility.</p>{testResult&&<strong className="test-result">{testResult}</strong>}</div><button className="button primary" disabled={testingEmail} onClick={()=>testEmail("primary")}>{testingEmail?"Testing…":"Save & test primary"}</button></div>
      <h3>Master sender settings</h3><div className="settings-grid compact-settings"><label>SMTP host<input name="smtpHost" placeholder="in-v3.mailjet.com" value={settings.smtpHost} onChange={change}/></label><label>Port<input name="smtpPort" inputMode="numeric" value={settings.smtpPort} onChange={change}/></label><label>Username<input name="smtpUser" autoComplete="off" value={settings.smtpUser} onChange={change}/></label><label>SMTP password<input name="smtpPassword" type="password" autoComplete="new-password" placeholder={settings.smtpPasswordConfigured?"Stored securely — enter only to replace":"Enter SMTP password"} value={settings.smtpPassword} onChange={change}/></label><label>From name<input name="fromName" value={settings.fromName} onChange={change}/></label><label>From email<input name="fromEmail" type="email" value={settings.fromEmail} onChange={change}/></label><label>Test recipient<input name="smtpTestRecipient" type="email" placeholder="Where should the test message go?" value={settings.smtpTestRecipient} onChange={change}/></label></div>
      <div className="alert-smtp-section"><h3>Independent delivery-failure alerts</h3><p>Optional. Use a different provider so an outage in the master service cannot suppress its own warning.</p><div className="settings-grid compact-settings"><label>Reseller alert recipient<input name="failureAlertEmail" type="email" value={settings.failureAlertEmail} onChange={change}/></label><label>Backup SMTP host<input name="alertSmtpHost" value={settings.alertSmtpHost} onChange={change}/></label><label>Backup SMTP port<input name="alertSmtpPort" inputMode="numeric" value={settings.alertSmtpPort} onChange={change}/></label><label>Backup SMTP user<input name="alertSmtpUser" autoComplete="off" value={settings.alertSmtpUser} onChange={change}/></label><label>Backup SMTP password<input name="alertSmtpPassword" type="password" autoComplete="new-password" placeholder={settings.alertSmtpPasswordConfigured?"Stored securely — enter only to replace":"Optional backup password"} value={settings.alertSmtpPassword} onChange={change}/></label><label>Backup from email<input name="alertFromEmail" type="email" value={settings.alertFromEmail} onChange={change}/></label></div><label className="check-row"><input type="checkbox" name="notifyEmailFailures" checked={settings.notifyEmailFailures} onChange={change}/> Alert the reseller administrator when the master delivery service fails</label><button className="button secondary backup-test-button" disabled={testingEmail} onClick={()=>testEmail("backup")}>{testingEmail?"Testing…":"Save & test backup"}</button></div><SaveRow saved={saved} save={save}/>
    </section></>}
  </div></section></main>;
}

function SaveRow({saved,save}:{saved:boolean;save:()=>void|Promise<void>}){return <div className="settings-save"><small>{saved?"Saved to the reseller account.":"Changes are private to the reseller account."}</small><button className="button primary" onClick={()=>void save()}>Save settings</button></div>}
function StatusItem({label,code,ready,optional=false}:{label:string;code:string;ready?:boolean;optional?:boolean}){return <div><span>{label}</span><strong className={ready?"secret-ready":"secret-missing"}>{ready?"Configured":optional?"Optional":"Missing"}</strong><code>{code}</code></div>}
