"use client";

import { ChangeEvent, useMemo, useState } from "react";
import { useMutation, useQuery } from "convex/react";
import { api } from "../../convex/_generated/api";
import type { Id } from "../../convex/_generated/dataModel";
import type { ReviewProvider } from "@/lib/demo-data";

type DraftReview={externalId?:string;reviewerName:string;rating:number;excerpt:string;reviewDate?:string;sourceLabel:string;sourceUrl:string;sourceProvider:ReviewProvider;isPublished:boolean};
const headers=["reviewer_name","rating","review_text","review_date","source","source_url","external_id","published"];

export function ReviewManager({businessId,slug}:{businessId:Id<"businesses">;slug:string}){
  const rows=useQuery(api.reviews.listForBusiness,{businessId});const importMany=useMutation(api.reviews.importMany);
  const[drafts,setDrafts]=useState<DraftReview[]>([]);const[message,setMessage]=useState("");const[busy,setBusy]=useState(false);
  const published=useMemo(()=>(rows??[]).filter(row=>row.isPublished),[rows]);
  async function chooseFile(event:ChangeEvent<HTMLInputElement>){const file=event.target.files?.[0];if(!file)return;try{const parsed=parseCsv(await file.text());setDrafts(parsed);setMessage(`${parsed.length} valid review${parsed.length===1?"":"s"} ready to import.`)}catch(error){setDrafts([]);setMessage(error instanceof Error?error.message:"The CSV could not be read.")}}
  async function runImport(){if(!drafts.length)return;setBusy(true);try{const result=await importMany({businessId,reviews:drafts});setMessage(`Import complete: ${result.added} added, ${result.updated} updated.`);setDrafts([]);void fetch("/api/reviews/import-notification",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({slug,count:result.added})})}catch(error){setMessage(error instanceof Error?error.message:"Import failed.")}finally{setBusy(false)}}
  function template(){const data=[headers.join(","),'"Jane Doe",5,"Excellent work and communication.",2026-09-01,Google,https://www.google.com/,google-123,true'].join("\n");const link=document.createElement("a");link.href=URL.createObjectURL(new Blob([data],{type:"text/csv"}));link.download="myroi-review-import-template.csv";link.click();setTimeout(()=>URL.revokeObjectURL(link.href),1000)}
  return <><div className="section-heading"><div><span className="eyebrow">Curated social proof</span><h2>Published reviews</h2></div><div className="review-import-actions"><button className="button" onClick={template}>Download CSV template</button><label className="button file-button">Choose CSV<input type="file" accept=".csv,text/csv" onChange={chooseFile}/></label><button className="button primary" disabled={!drafts.length||busy} onClick={runImport}>{busy?"Importing…":drafts.length?`Import ${drafts.length} reviews`:"Import reviews"}</button></div></div><p className="panel-intro">Import CSV exports from Google, Yelp, your scraper, or another provider. Re-importing the same external ID updates the review instead of duplicating it.</p>{message&&<div className="action-message">{message}</div>}<div className="review-row-grid">{published.map(review=><article className="mini-review" key={review._id}><span className="stars">{"★".repeat(review.rating)}</span><p>“{review.excerpt}”</p><small>{review.reviewerName} · {review.sourceLabel}</small></article>)}{rows&&rows.length===0&&<div className="empty-state">No reviews imported yet. Download the template to see the accepted format.</div>}</div></>;
}

function parseCsv(text:string):DraftReview[]{const table=parseRows(text.replace(/^\uFEFF/,""));if(table.length<2)throw new Error("The CSV has no review rows.");const keys=table[0].map(value=>normalize(value));const find=(...names:string[])=>names.map(name=>keys.indexOf(name)).find(index=>index>=0)??-1;const name=find("reviewername","name","author");const rating=find("rating","stars","score");const excerpt=find("reviewtext","review","text","excerpt","comment");if(name<0||rating<0||excerpt<0)throw new Error("Required columns: reviewer_name, rating, and review_text.");const date=find("reviewdate","date");const source=find("source","platform","provider");const sourceUrl=find("sourceurl","reviewurl","url");const external=find("externalid","id");const published=find("published","ispublished");return table.slice(1).filter(row=>row.some(Boolean)).map((row,index)=>{const stars=Number(row[rating]);if(!Number.isFinite(stars)||stars<1||stars>5)throw new Error(`Row ${index+2} has an invalid rating.`);const sourceLabel=(row[source]||"Imported").trim();const candidateUrl=sourceUrl>=0?row[sourceUrl]?.trim()||"":"";return{reviewerName:(row[name]||"Anonymous").trim(),rating:Math.round(stars),excerpt:(row[excerpt]||"").trim(),reviewDate:date>=0?row[date]?.trim()||undefined:undefined,sourceLabel,sourceUrl:isHttps(candidateUrl)?candidateUrl:"",externalId:external>=0?row[external]?.trim()||undefined:undefined,sourceProvider:providerFor(sourceLabel),isPublished:published<0?true:/^(true|yes|1|published)$/i.test(row[published]||"")}}).filter(row=>row.excerpt)}
function parseRows(text:string){const rows:string[][]=[];let row:string[]=[],cell="",quoted=false;for(let i=0;i<text.length;i++){const char=text[i];if(char==='"'){if(quoted&&text[i+1]==='"'){cell+='"';i++}else quoted=!quoted}else if(char===","&&!quoted){row.push(cell);cell=""}else if((char==="\n"||char==="\r")&&!quoted){if(char==="\r"&&text[i+1]==="\n")i++;row.push(cell);rows.push(row);row=[];cell=""}else cell+=char}if(cell||row.length){row.push(cell);rows.push(row)}return rows}
function normalize(value:string){return value.toLowerCase().replace(/[^a-z0-9]/g,"")}
function isHttps(value:string){try{return new URL(value).protocol==="https:"}catch{return false}}
function providerFor(value:string):ReviewProvider{const key=value.toLowerCase();return(["google","facebook","yelp","tripadvisor","trustpilot","g2","capterra","healthgrades","diamond"] as ReviewProvider[]).find(item=>key.includes(item))??"custom"}
